#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Fail due to there are less than or more than 2 parameter"
	exit 1
fi

if [ -f "$1" ]; then
	echo "$1 is a file in this current directory"
fi

if [ -d "$2" ]; then
	echo "$2 is a directory in this current directory"
fi

exit 0
